### ISSUE TITLE
how about performance comparsion with rapidjson?

### ISSUE THREAD

**Issue by Harold2017** [stephenberry/json_performance#3]
Usually, i think rapidjson has the best performance, would you mind comparing your lib with it?

[rapidjson](https://github.com/Tencent/rapidjson)

[benchmark](https://github.com/miloyip/nativejson-benchmark)

**Comment by stephenberry** [comment]
I'll add a benchmark at some point, but daw_json_link is over twice as fast as rapidjson [see chart](https://github.com/beached/daw_json_link/blob/release/docs/images/kostya_bench_chart_2021_04_03.png)
, and glaze is faster than daw_json_link. So, I expect glaze to be multiple times faster.

**Comment by Harold2017** [comment]
Wow, amazing, i never tried daw_json_link before, thx for the link.
