### ISSUE TITLE
Interested in yyjson?

### ISSUE THREAD

**Issue by toge** [stephenberry/json_performance#8]
I try comparing yyjson with other parsers by using this benchmark code.

I wrote easy code and am in the process of checking the validity of the code, but yyjson seems to run quite fast.
https://github.com/toge/json_performance/tree/add-yyjson

Could you merge it into the benchmark?
If you are going to write your own code, you may reference it.
I will create a PR if necessary.

**Comment by stephenberry** [comment]
Thanks! This is great, we've looked a lot at yyjson when writing glaze, they do a great job focusing on performance.
I'll let you know if I'd like a pull request, but I can probably just copy your implementation.

**Comment by stephenberry** [comment]
I merged your additions, thanks!

**Comment by toge** [comment]
Thanks a lot!
